spring:
  application:
    name: avatar-service
  zipkin:
    base-url: http://localhost:9411
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Avatar

server:
  port: 9001

eureka:
    client:
      service-url:
        defaultZone:  http://localhost:8761/eureka