apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-module
  labels:
    app: rating-module
  replicas: 1
  selector:
    matchLabels:
      app: rating-module
  template:
    metadata:
      labels:
        app: rating-module
    spec:
      containers:
        - name: rating-module
          image: vishwaghimire/rating-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: APP_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: ea-configmap
                  key: app_profile
            - name: POSTGRES_URL
              valueFrom:
                configMapKeyRef:
                  name: ea-configmap
                  key: postgres_url
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: ea-configmap
                  key: postgres_port
            - name: POSTGRES_DATABASE_NAME_USER
              valueFrom:
                configMapKeyRef:
                  name: ea-configmap
                  key: postgres_database_name_user
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ea-postgres-secret
                  key: postgres-root-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ea-postgres-secret
                  key: postgres-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: rating-service
spec:
  selector:
    app: rating-module
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080