

spring:
  application:
    name: email-service
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    host: smtp-mail.outlook.com
    username: avyrwl1@outlook.com
    protocol: smtp
    password: '%1da15cs177%'
    test-connection: false
    port: 587
    default-encoding: UTF-8



eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka
server:
  port: 9092